# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_heck_wrappers", use_symbols = TRUE, package_name = "heck")

#' @docType package
#' @usage NULL
#' @useDynLib heck, .registration = TRUE
NULL

to_snek_case <- function(x) .Call(wrap__to_snek_case, x)


# nolint end
